appid: leanfried.sbgui.v1.0.4
calibration:
  flowRateFolder: C:/Users/lmf1/OneDrive - National Institute of Standards and Technology
    (NIST)/NIST/data/material properties/flow rates
  initDensity: 1
  initDiam: '0.603'
  initSpeed: '40'
camera:
  diag: 1
files:
  createSubfolders: true
  dateFormat: '%y%m%d'
  duplicateFormat: '{0:0=3d}'
  includeDateRadio: 0
  includeSBInFile: true
  includeSBRadio: 2
  includeSampleInFile: true
  includeSampleInFolder: true
  includeTimeInFile: true
  save: C:\Users\lmf1\Videos\Shopbot Videos\vels mineral LapRD
  separator: _
  timeFormat: '%y%m%d_%H%M%S_%f'
fluigent:
  colors:
  - '#3f8dd1'
  - '#b0401e'
  - '#3e8a5b'
  - '#b8a665'
  dt: 50
  pmax: 7000
  savePressure: true
  trange: 60
layout:
  save: true
savePressure: true
shopbot:
  autoplay: false
  dt: 50
  sbpFolder: C:\Users\lmf1\Documents\GitHub\ShopbotPyQt\SBP files
  sbpName: C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/singleLinesNoZig_2.5.sbp
