appid: leanfried.sbgui.v1.0.4
calibration:
  flowRateFolder: C:/Users/lmf1/OneDrive - National Institute of Standards and Technology
    (NIST)/NIST/data/material properties/flow rates
  initDensity: 1
  initDiam: '0.603'
  initSpeed: '40.0'
camera:
  bascam:
    fps: 100.0
  diag: 1
files:
  createSubfolders: true
  dateFormat: '%y%m%d'
  duplicateFormat: '{0:0=3d}'
  includeDateRadio: 0
  includeSBInFile: true
  includeSBRadio: 1
  includeSampleInFile: true
  includeSampleInFolder: true
  includeTimeInFile: true
  save: C:\Users\lmf1\Videos\Shopbot Videos\test
  separator: _
  tag: test
  timeFormat: '%y%m%d_%H%M%S_%f'
fluigent:
  colors:
  - '#3f8d88'
  - '#b0401e'
  - '#3e8a5b'
  - '#b8a665'
  dt: 50
  pmax: 6000
  savePressure: true
  trange: 60
layout:
  save: true
savePressure: true
shopbot:
  autoplay: false
  critTimeOff: 0
  critTimeOn: 0.1
  dt: 50
  includePositionInTable: true
  meta:
    camera_magnification:
      units: x
      value: '0.5'
    camera_position:
      units: None
      value: side
    nozzle_inner_diameter:
      units: mm
      value: '0.603'
    nozzle_length:
      units: mm
      value: '38'
    nozzle_material:
      units: None
      value: stainless steel
    nozzle_outer_diameter:
      units: mm
      value: '0.908'
    tubing_inner_diameter:
      units: mm
      value: '0.79375'
    tubing_length:
      units: mm
      value: '280'
    tubing_material:
      units: None
      value: PTFE
  sbpFiles:
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP_files/calibration/timing_calibration.sbp
  sbpFolder: C:\Users\lmf1\Documents\GitHub\ShopbotPyQt\SBP_files
  sbpName: C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP_files/calibration/timing_calibration.sbp
  showFolder: false
  zeroDist: 0.1
