appid: leanfried.sbgui.v1.0.4
calibration:
  flowRateFolder: C:/Users/lmf1/OneDrive - National Institute of Standards and Technology
    (NIST)/NIST/data/material properties/flow rates
  initDensity: 1
  initDiam: '0.603'
  initSpeed: '10.0'
camera:
  bascam:
    fps: 0
  diag: 1
files:
  createSubfolders: true
  dateFormat: '%y%m%d'
  duplicateFormat: '{0:0=3d}'
  includeDateRadio: 0
  includeSBInFile: true
  includeSBRadio: 1
  includeSampleInFile: true
  includeSampleInFolder: true
  includeTimeInFile: true
  save: C:\Users\lmf1\Videos\Shopbot Videos\test
  separator: _
  tag: test
  timeFormat: '%y%m%d_%H%M%S_%f'
fluigent:
  colors:
  - '#3f8d88'
  - '#b0401e'
  - '#3e8a5b'
  - '#b8a665'
  dt: 50
  pmax: 6000
  savePressure: true
  trange: 60
layout:
  save: true
savePressure: true
shopbot:
  autoplay: false
  dt: 50
  sbpFiles:
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleHoriz_0.5_0.500.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleHoriz_0.5_0.625.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleHoriz_0.5_0.750.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleHoriz_0.5_0.875.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleHoriz_0.5_1.000.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleHoriz_0.5_1.250.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleHoriz_0_0.500.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleHoriz_0_0.625.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleHoriz_0_0.750.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleHoriz_0_0.875.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleHoriz_0_1.000.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleHoriz_0_1.250.sbp
  - BREAK
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleHorizPics.sbp
  - BREAK
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleVert_0.5_0.500.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleVert_0.5_0.625.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleVert_0.5_0.750.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleVert_0.5_0.875.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleVert_0.5_1.000.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleVert_0.5_1.250.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleVert_0_0.500.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleVert_0_0.625.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleVert_0_0.750.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleVert_0_0.875.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleVert_0_1.000.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleVert_0_1.250.sbp
  - BREAK
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleVertPics.sbp
  - BREAK
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesHoriz_0.500.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesHoriz_0.625.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesHoriz_0.750.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesHoriz_0.875.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesHoriz_1.000.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesHoriz_1.250.sbp
  - BREAK
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesHorizPics.sbp
  - BREAK
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesVert_0.500.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesVert_0.625.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesVert_0.750.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesVert_0.875.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesVert_1.000.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesVert_1.250.sbp
  - BREAK
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesVertPics.sbp
  - BREAK
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesXS_+y_0.500.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesXS_+y_0.625.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesXS_+y_0.750.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesXS_+y_0.875.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesXS_+y_1.000.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesXS_+y_1.250.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesXS_+z_0.500.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesXS_+z_0.625.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesXS_+z_0.750.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesXS_+z_0.875.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesXS_+z_1.000.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesXS_+z_1.250.sbp
  - BREAK
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/tripleLinesXSPics.sbp
  - BREAK
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/crossUnder_0.5_0.500.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/crossUnder_0.5_0.625.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/crossUnder_0.5_0.750.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/crossUnder_0.5_0.875.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/crossUnder_0.5_1.000.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/crossUnder_0.5_1.250.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/crossUnder_0_0.500.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/crossUnder_0_0.625.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/crossUnder_0_0.750.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/crossUnder_0_0.875.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/crossUnder_0_1.000.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/crossUnder_0_1.250.sbp
  - BREAK
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/tripleLinesUnder_0.500.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/tripleLinesUnder_0.625.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/tripleLinesUnder_0.750.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/tripleLinesUnder_0.875.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/tripleLinesUnder_1.000.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesUnder/tripleLinesUnder_1.250.sbp
  - C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/singleLines/speed test.sbp
  sbpFolder: C:\Users\lmf1\Documents\GitHub\ShopbotPyQt\SBP files
  sbpName: C:/Users/lmf1/Documents/GitHub/ShopbotPyQt/SBP files/tripleLinesSide/crossDoubleHoriz_0.5_0.500.sbp
  showFolder: false
